[package]
name = "fuckDebug"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
windows = { version = "0.51", features = ["Win32_Foundation", "Win32_System_Memory", "Win32_System_Diagnostics_Debug"] }

[[bin]]
name = "fuckDebug"
path = "src/main.rs"
